name: rag_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - aom=3.9.1
  - asttokens=2.4.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - cairo=1.16.0
  - certifi=2024.7.4
  - charset-normalizer=3.3.2
  - comm=0.2.2
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.6
  - dav1d=1.2.1
  - debugpy=1.8.5
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - expat=2.6.2
  - ffmpeg=4.3
  - filelock=3.13.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.3.0
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - graphite2=1.3.14
  - harfbuzz=4.3.0
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.2.0
  - importlib_metadata=8.2.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.26.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.11.0.15
  - libcurand=10.3.7.37
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.21
  - libdrm=2.4.122
  - libedit=3.1.20191231
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=14.1.0
  - libglib=2.78.4
  - libgomp=14.1.0
  - libhwloc=2.11.1
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libnvjpeg=11.9.0.86
  - libopenvino=2024.3.0
  - libopenvino-auto-batch-plugin=2024.3.0
  - libopenvino-auto-plugin=2024.3.0
  - libopenvino-hetero-plugin=2024.3.0
  - libopenvino-intel-cpu-plugin=2024.3.0
  - libopenvino-intel-gpu-plugin=2024.3.0
  - libopenvino-intel-npu-plugin=2024.3.0
  - libopenvino-ir-frontend=2024.3.0
  - libopenvino-onnx-frontend=2024.3.0
  - libopenvino-paddle-frontend=2024.3.0
  - libopenvino-pytorch-frontend=2024.3.0
  - libopenvino-tensorflow-frontend=2024.3.0
  - libopenvino-tensorflow-lite-frontend=2024.3.0
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libstdcxx-ng=14.1.0
  - libtasn1=4.19.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libva=2.22.0
  - libvpx=1.14.1
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxcrypt=4.4.36
  - libxml2=2.13.1
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - numpy=1.26.4
  - numpy-base=1.26.4
  - ocl-icd=2.3.2
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.3.1
  - p11-kit=0.24.1
  - packaging=24.1
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.43.2
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.47
  - psutil=6.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pugixml=1.14
  - pure_eval=0.2.3
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.11.9
  - python_abi=3.11
  - pytorch=2.2.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - pyzmq=26.1.0
  - readline=8.2
  - requests=2.32.3
  - setuptools=72.1.0
  - six=1.16.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - stack_data=0.6.2
  - svt-av1=2.1.2
  - sympy=1.12
  - tbb=2021.12.0
  - tk=8.6.14
  - torchaudio=2.2.1
  - torchtriton=2.2.0
  - torchvision=0.17.1
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - urllib3=2.2.2
  - wayland=1.23.0
  - wayland-protocols=1.36
  - wcwidth=0.2.13
  - wheel=0.44.0
  - x264=1!164.3095
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - accelerate==0.33.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.3.5
      - aiohttp==3.10.2
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyascii==0.3.2
      - anyio==4.4.0
      - attrs==24.2.0
      - audioread==3.0.1
      - babel==2.16.0
      - bangla==0.0.2
      - beautifulsoup4==4.12.3
      - blinker==1.8.2
      - blis==0.7.11
      - bnnumerizer==0.0.2
      - bnunicodenormalizer==0.1.7
      - catalogue==2.0.10
      - cffi==1.17.0
      - click==8.1.7
      - cloudpathlib==0.18.1
      - confection==0.1.5
      - contourpy==1.2.1
      - coqpit==0.0.17
      - cycler==0.12.1
      - cymem==2.0.8
      - cython==3.0.11
      - dataclasses-json==0.6.7
      - datasets==2.20.0
      - dateparser==1.1.8
      - dill==0.3.8
      - diskcache==5.6.3
      - dnspython==2.6.1
      - docopt==0.6.2
      - einops==0.8.0
      - email-validator==2.2.0
      - encodec==0.1.1
      - fastapi==0.112.0
      - fastapi-cli==0.0.5
      - ffmpy==0.4.0
      - flask==3.0.3
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - fsspec==2024.5.0
      - g2pkk==0.1.2
      - gradio==4.41.0
      - gradio-client==1.3.0
      - greenlet==3.0.3
      - grpcio==1.65.4
      - gruut==2.2.3
      - gruut-ipa==0.13.0
      - gruut-lang-de==2.0.1
      - gruut-lang-en==2.0.1
      - gruut-lang-es==2.0.1
      - gruut-lang-fr==2.0.2
      - h11==0.14.0
      - hangul-romanize==0.1.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.24.5
      - importlib-resources==6.4.0
      - inflect==7.3.1
      - itsdangerous==2.2.0
      - jamo==0.4.1
      - jieba==0.42.1
      - joblib==1.4.2
      - jsonlines==1.2.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - kiwisolver==1.4.5
      - langchain==0.2.12
      - langchain-community==0.2.11
      - langchain-core==0.2.29
      - langchain-text-splitters==0.2.2
      - langcodes==3.4.0
      - langgraph==0.2.3
      - langgraph-checkpoint==1.0.2
      - langsmith==0.1.98
      - language-data==1.2.0
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - llama-cpp-python==0.2.87
      - llvmlite==0.43.0
      - marisa-trie==1.2.0
      - markdown==3.6
      - markdown-it-py==3.0.0
      - marshmallow==3.21.3
      - matplotlib==3.9.1.post1
      - mdurl==0.1.2
      - more-itertools==10.4.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - multiprocess==0.70.16
      - murmurhash==1.0.10
      - mypy-extensions==1.0.0
      - networkx==2.8.8
      - ngrok==1.4.0
      - nltk==3.8.2
      - num2words==0.5.13
      - numba==0.60.0
      - ollama==0.3.1
      - openai-whisper==20231117
      - orjson==3.10.7
      - pandas==1.5.3
      - pooch==1.8.2
      - preshed==3.0.9
      - protobuf==4.25.4
      - pyarrow==17.0.0
      - pyarrow-hotfix==0.6
      - pycparser==2.22
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pydub==0.25.1
      - pynndescent==0.5.13
      - pyparsing==3.1.2
      - pypinyin==0.52.0
      - pysbd==0.3.4
      - python-crfsuite==0.9.10
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.9
      - pytz==2024.1
      - regex==2024.7.24
      - rich==13.7.1
      - ruff==0.5.7
      - safetensors==0.4.4
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - semantic-version==2.10.0
      - sentence-transformers==3.0.1
      - shellingham==1.5.4
      - smart-open==7.0.4
      - sniffio==1.3.1
      - sounddevice==0.4.7
      - soundfile==0.12.1
      - soupsieve==2.5
      - soxr==0.4.0
      - spacy==3.7.5
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlalchemy==2.0.32
      - srsly==2.4.8
      - starlette==0.37.2
      - sudachidict-core==20240716
      - sudachipy==0.6.8
      - tenacity==8.5.0
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - thinc==8.2.5
      - threadpoolctl==3.5.0
      - tiktoken==0.7.0
      - tokenizers==0.19.1
      - tomlkit==0.12.0
      - tqdm==4.66.5
      - trainer==0.0.36
      - transformers==4.44.0
      - tts==0.22.0
      - typeguard==4.3.0
      - typer==0.12.3
      - typing-inspect==0.9.0
      - tzdata==2024.1
      - tzlocal==5.2
      - umap-learn==0.5.6
      - unidecode==1.3.8
      - uvicorn==0.30.5
      - uvloop==0.19.0
      - wasabi==1.1.3
      - watchfiles==0.23.0
      - weasel==0.4.1
      - websockets==12.0
      - werkzeug==3.0.3
      - wrapt==1.16.0
      - xxhash==3.4.1
      - yarl==1.9.4
