name: rag_env
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2024.6.2
  - charset-normalizer=2.0.4
  - cpuonly=2.0=0
  - expat=2.6.2
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.2.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.14
  - pillow=10.3.0
  - pip=24.0
  - pysocks=1.7.1
  - python=3.12.4
  - pytorch=2.3.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.32.2
  - setuptools=69.5.1
  - sqlite=3.45.3
  - sympy=1.12
  - tbb=2021.8.0
  - tk=8.6.14
  - torchaudio=2.3.1
  - torchvision=0.18.1
  - typing_extensions=4.11.0
  - urllib3=2.2.2
  - wheel=0.43.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - accelerate==0.31.0
      - aiofiles==23.2.1
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - altair==5.3.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.8
      - anyio==4.4.0
      - asgiref==3.8.1
      - attrs==23.2.0
      - backoff==2.2.1
      - bcrypt==4.1.3
      - beautifulsoup4==4.12.3
      - bitarray==2.9.2
      - bitsandbytes==0.43.1
      - build==1.2.1
      - cachetools==5.3.3
      - cffi==1.16.0
      - chroma-hnswlib==0.7.3
      - chromadb==0.5.3
      - click==8.1.7
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contourpy==1.2.1
      - cycler==0.12.1
      - cython==3.0.10
      - dataclasses-json==0.6.7
      - deprecated==1.2.14
      - dnspython==2.6.1
      - docx2txt==0.8
      - email-validator==2.2.0
      - fairseq==0.12.2
      - fastapi==0.111.0
      - fastapi-cli==0.0.4
      - ffmpy==0.3.2
      - flatbuffers==24.3.25
      - fonttools==4.53.0
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - google-auth==2.30.0
      - googleapis-common-protos==1.63.2
      - gradio==4.37.2
      - gradio-client==1.0.2
      - greenlet==3.0.3
      - grpcio==1.64.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.23.4
      - humanfriendly==10.0
      - hydra-core==1.0.7
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - kubernetes==30.1.0
      - langchain==0.2.6
      - langchain-community==0.2.6
      - langchain-core==0.2.10
      - langchain-text-splitters==0.2.2
      - langgraph==0.1.4
      - langsmith==0.1.82
      - lxml==5.2.2
      - markdown-it-py==3.0.0
      - marshmallow==3.21.3
      - matplotlib==3.9.0
      - mdurl==0.1.2
      - mmh3==4.1.0
      - monotonic==1.6
      - multidict==6.0.5
      - mypy-extensions==1.0.0
      - nest-asyncio==1.6.0
      - ngrok==1.3.0
      - oauthlib==3.2.2
      - ollama==0.2.1
      - omegaconf==2.0.6
      - onnxruntime==1.18.1
      - opentelemetry-api==1.25.0
      - opentelemetry-exporter-otlp-proto-common==1.25.0
      - opentelemetry-exporter-otlp-proto-grpc==1.25.0
      - opentelemetry-instrumentation==0.46b0
      - opentelemetry-instrumentation-asgi==0.46b0
      - opentelemetry-instrumentation-fastapi==0.46b0
      - opentelemetry-proto==1.25.0
      - opentelemetry-sdk==1.25.0
      - opentelemetry-semantic-conventions==0.46b0
      - opentelemetry-util-http==0.46b0
      - orjson==3.10.5
      - overrides==7.7.0
      - packaging==24.1
      - pandas==2.2.2
      - portalocker==2.10.0
      - posthog==3.5.0
      - protobuf==4.25.3
      - psutil==6.0.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pycparser==2.22
      - pydantic==2.7.4
      - pydantic-core==2.18.4
      - pydub==0.25.1
      - pygments==2.18.0
      - pyngrok==7.1.6
      - pyparsing==3.1.2
      - pypdf==4.2.0
      - pypika==0.48.9
      - pyproject-hooks==1.1.0
      - pysqlite3==0.5.3
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.9
      - pytz==2024.1
      - referencing==0.35.1
      - regex==2024.5.15
      - requests-oauthlib==2.0.0
      - rich==13.7.1
      - rpds-py==0.18.1
      - rsa==4.9
      - ruff==0.5.0
      - sacrebleu==2.4.2
      - safetensors==0.4.3
      - scikit-learn==1.5.0
      - scipy==1.14.0
      - semantic-version==2.10.0
      - sentence-transformers==3.0.1
      - shellingham==1.5.4
      - six==1.16.0
      - sniffio==1.3.1
      - soupsieve==2.5
      - sqlalchemy==2.0.31
      - starlette==0.37.2
      - tabulate==0.9.0
      - tenacity==8.4.2
      - threadpoolctl==3.5.0
      - tokenizers==0.19.1
      - tomlkit==0.12.0
      - toolz==0.12.1
      - tqdm==4.66.4
      - transformers==4.42.3
      - typer==0.12.3
      - typing-inspect==0.9.0
      - tzdata==2024.1
      - ujson==5.10.0
      - uvicorn==0.30.1
      - uvloop==0.19.0
      - watchfiles==0.22.0
      - websocket-client==1.8.0
      - websockets==11.0.3
      - wrapt==1.16.0
      - yarl==1.9.4
      - zipp==3.19.2