nllb:
  model_config:
    translator_path: 
    translitarator_path: 
    torch_dtype: torch.float16
    low_cpu_mem_usage: True
    load_in_4bit: False
    load_in_8bit: False

m2m100:
  model_config:
    translator_path: 
    translitarator_path: 
    torch_dtype: torch.float16
    low_cpu_mem_usage: True
    load_in_4bit: False
    load_in_8bit: False

marian_mt:
  model_config:
    en_mul_translator_path: 
    mul_en_translator_path: 
    translitarator_path: 
    torch_dtype: torch.float16
    low_cpu_mem_usage: True
    load_in_4bit: False
    load_in_8bit: False
    device: cuda